spring:
  application:
    name:weatherShow
  datasource:
    url: jdbc:mysql://localhost:3306/weatherdb?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234


mybatis: # 或者 mybatis: 如果你没用 Plus 的特有功能
  # mapper-locations 应该与 configuration 同级
  mapper-locations: classpath*:com/example/weathershow/mapper/*.xml

  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

server:
  port: 8080